### ISSUE TITLE
Instagram access token

### ISSUE THREAD

**Issue by jklue** [aryehraber/statamic-instagrizzle#1]
Thank you for the plugin! Do you know if this works with the new Instagram policy that requires an access token?

**Comment by aryehraber** [comment]
Hi @lukehatfield!

To be honest, I'm not completely familiar with Instagram's policy's atm. This Addon is basically a "quick and dirty" way to get around Instagram's API keys/tokens by using unofficial data streams from Instagram's own API. Unfortunately, that means when they change / remove things, the Addon breaks... which I believe happened recently and I haven't gotten around to pathing it up. Maybe this happened inline with their new policy changes?

If you have any ideas on improvements, or feel like building an access-token integration, please go ahead! I'd be happy to accept a PR 😊
